[project]
name = "wattpad-archiver"
version = "0.1.0"
description = "Downloads your wattpad library to disk"
authors = [{ name = "MRtecno98", email = "mr.tecno98@gmail.com" }]
requires-python = ">=3.10,<4"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "requests>=2.28.1,<3",
    "EbookLib>=0.18,<=0.20",
    "beautifulsoup4>=4.11.1,<5",
]

[dependency-groups]
dev = []

[tool.uv]
package = false

[build-system]
requires = ["uv_build>=0.8.15,<0.9.0"]
build-backend = "uv_build"
